name: Textus Design Solutions
favicon: null
layout_spectrum: 0.99829
typography_spectrum: 0.57983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1416'
    - '#828f75'
    - '#eccc79'
    - '#aeb490'
    - '#556564'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
